# Generated by Django 3.0.4 on 2020-03-13 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20200307_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='search_for',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
