# Generated by Django 3.0.4 on 2020-03-23 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20200323_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='something_about_you',
            new_name='status',
        ),
    ]
